apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java
  template:
    metadata:
      labels:
        app: my-java
    spec:
      containers:
      - name: my-java
        image: techdocker24/java
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: my-java
spec:
  selector:
    app: my-java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
